const assert = require("assert");
const app = require("../../src/app");

let usersRefData = [
  {
    name: "Standard User",
    email: "standard@example.com",
    password: "password",
  },
];

describe("payments service", async () => {
  let thisService;
  let paymentCreated;
  let usersServiceResults;
  let users;

  const customerAddressCreated = await app.service("customerAddress").Model.create({"paymentNumber":"new value","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value"});
const customerCreated = await app.service("customer").Model.create({"paymentNumber":"new value","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":`${customerAddressCreated._id}`,"addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z"});
const customerCreated = await app.service("customer").Model.create({"paymentNumber":"new value","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId"});
const customerCreated = await app.service("customer").Model.create({"paymentNumber":"new value","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":`${customerCreated._id}`,"phoneContact":"parentObjectId"});
const couponsCreated = await app.service("coupons").Model.create({"paymentNumber":"new value","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z"});
const productPriceCreated = await app.service("productPrice").Model.create({"paymentNumber":"new value","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value"});
const orderCreated = await app.service("order").Model.create({"paymentNumber":"new value","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23});
const orderCreated = await app.service("order").Model.create({"paymentNumber":"new value","orderNumber":"new value","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":23,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId"});
const typeOfProductCreated = await app.service("typeOfProduct").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"new value","typeOfProduct":"parentObjectId","productType":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z"});
const productSizeCreated = await app.service("productSize").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":`${inventoryCreated._id}`,"sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId"});
const productColourCreated = await app.service("productColour").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":"parentObjectId","colorName":"new value","colorCode":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value"});
const productPriceCreated = await app.service("productPrice").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":"parentObjectId"});
const productPriceCreated = await app.service("productPrice").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":"parentObjectId"});
const productsCreated = await app.service("products").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":`${productPriceCreated._id}`,"status":["new value"]});
const categoryCreated = await app.service("category").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":`${productPriceCreated._id}`,"status":["new value"]});
const productsCreated = await app.service("products").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"]});
const typeOfProductCreated = await app.service("typeOfProduct").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value"});
const productPriceCreated = await app.service("productPrice").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId"});
const checkoutCreated = await app.service("checkout").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":`${productPriceCreated._id}`,"netTotal":"parentObjectId"});
const orderProductCreated = await app.service("orderProduct").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":`${productPriceCreated._id}`,"netTotal":`${checkoutCreated._id}`});
const checkoutCreated = await app.service("checkout").Model.create({"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":"parentObjectId","productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":`${productPriceCreated._id}`,"netTotal":`${checkoutCreated._id}`});

  beforeEach(async () => {
    thisService = await app.service("payments");

    // Create users here
    usersServiceResults = await app.service("users").Model.create(usersRefData);
    users = {
      createdBy: usersServiceResults[0]._id,
      updatedBy: usersServiceResults[0]._id,
    };
  });

  after(async () => {
    if (usersServiceResults) {
      await Promise.all(
        usersServiceResults.map((i) =>
          app.service("users").Model.findByIdAndDelete(i._id)
        )
      );
    }
  });

  it("registered the service", () => {
    assert.ok(thisService, "Registered the service (payments)");
  });

  describe("#create", () => {
    const options = {"paymentNumber":"new value","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.429Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.430Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.430Z","tax":23,"paymentMethod":"new value","amount":`${checkoutCreated._id}`,"productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.431Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":`${productPriceCreated._id}`,"netTotal":`${checkoutCreated._id}`,"paidAt":"2026-10-01T15:57:14.433Z"};

    beforeEach(async () => {
      paymentCreated = await thisService.Model.create({...options, ...users});
    });

    it("should create a new payment", () => {
      assert.strictEqual(paymentCreated.paymentNumber, options.paymentNumber);
assert.strictEqual(paymentCreated.orderNumber.toString(), options.orderNumber.toString());
assert.strictEqual(paymentCreated.paymentMethod, options.paymentMethod);
assert.strictEqual(paymentCreated.amount.toString(), options.amount.toString());
assert.strictEqual(paymentCreated.paidAt.toISOString(), options.paidAt);
    });
  });

  describe("#get", () => {
    it("should retrieve a payment by ID", async () => {
      const retrieved = await thisService.Model.findById(paymentCreated._id);
      assert.strictEqual(retrieved._id.toString(), paymentCreated._id.toString());
    });
  });

  describe("#update", () => {
    const options = {"paymentNumber":"updated value","orderNumber":`${orderCreated._id}`,"paymentMethod":"updated value","amount":`${checkoutCreated._id}`,"paidAt":"2026-10-01T15:57:14.433Z"};

    it("should update an existing payment ", async () => {
      const paymentUpdated = await thisService.Model.findByIdAndUpdate(
        paymentCreated._id, 
        options, 
        { new: true } // Ensure it returns the updated doc
      );
      assert.strictEqual(paymentUpdated.paymentNumber, options.paymentNumber);
assert.strictEqual(paymentUpdated.orderNumber.toString(), options.orderNumber.toString());
assert.strictEqual(paymentUpdated.paymentMethod, options.paymentMethod);
assert.strictEqual(paymentUpdated.amount.toString(), options.amount.toString());
assert.strictEqual(paymentUpdated.paidAt.toISOString(), options.paidAt);
    });
  });

  describe("#delete", async () => {
    it("should delete a payment", async () => {
      await app
        .service("users")
        .Model.findByIdAndDelete(usersServiceResults._id);

      await app.service("customerAddress").Model.findByIdAndDelete(customerAddressCreated._id);
await app.service("customer").Model.findByIdAndDelete(customerCreated._id);
await app.service("coupons").Model.findByIdAndDelete(couponsCreated._id);
await app.service("productPrice").Model.findByIdAndDelete(productPriceCreated._id);
await app.service("order").Model.findByIdAndDelete(orderCreated._id);
await app.service("typeOfProduct").Model.findByIdAndDelete(typeOfProductCreated._id);
await app.service("inventory").Model.findByIdAndDelete(inventoryCreated._id);
await app.service("productSize").Model.findByIdAndDelete(productSizeCreated._id);
await app.service("productColour").Model.findByIdAndDelete(productColourCreated._id);
await app.service("products").Model.findByIdAndDelete(productsCreated._id);
await app.service("category").Model.findByIdAndDelete(categoryCreated._id);
await app.service("checkout").Model.findByIdAndDelete(checkoutCreated._id);
await app.service("orderProduct").Model.findByIdAndDelete(orderProductCreated._id);;

      const paymentDeleted = await thisService.Model.findByIdAndDelete(paymentCreated._id);
      assert.strictEqual(paymentDeleted._id.toString(), paymentCreated._id.toString());
    });
  });
});