const assert = require("assert");
const app = require("../../src/app");

let usersRefData = [
  {
    name: "Standard User",
    email: "standard@example.com",
    password: "password",
  },
];

describe("returnsRefunds service", async () => {
  let thisService;
  let returnsRefundCreated;
  let usersServiceResults;
  let users;

  const customerAddressCreated = await app.service("customerAddress").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value"});
const customerCreated = await app.service("customer").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":`${customerAddressCreated._id}`,"addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z"});
const customerCreated = await app.service("customer").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":"parentObjectId"});
const customerCreated = await app.service("customer").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":"parentObjectId"});
const couponsCreated = await app.service("coupons").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z"});
const productPriceCreated = await app.service("productPrice").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value"});
const orderCreated = await app.service("order").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23});
const typeOfProductCreated = await app.service("typeOfProduct").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"new value","typeOfProduct":"parentObjectId","productType":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z"});
const productSizeCreated = await app.service("productSize").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":`${inventoryCreated._id}`,"sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId"});
const productColourCreated = await app.service("productColour").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":"parentObjectId","colorName":"new value","colorCode":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value"});
const productPriceCreated = await app.service("productPrice").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":"parentObjectId"});
const productPriceCreated = await app.service("productPrice").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":"parentObjectId"});
const productsCreated = await app.service("products").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":`${productPriceCreated._id}`,"status":["new value"]});
const categoryCreated = await app.service("category").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":`${productPriceCreated._id}`,"status":["new value"]});
const productsCreated = await app.service("products").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"]});
const typeOfProductCreated = await app.service("typeOfProduct").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value"});
const productPriceCreated = await app.service("productPrice").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.449Z","tax":23,"productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId"});
const orderCreated = await app.service("order").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"new value","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":23,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.450Z","tax":23,"productName":"new value","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":`${productPriceCreated._id}`,"netTotal":"parentObjectId"});
const orderProductCreated = await app.service("orderProduct").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.450Z","tax":23,"productName":"parentObjectId","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":"parentObjectId","paymentMethod":"new value"});
const checkoutCreated = await app.service("checkout").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.450Z","tax":23,"productName":"parentObjectId","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":"parentObjectId","paymentMethod":"new value"});
const orderProductCreated = await app.service("orderProduct").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.450Z","tax":23,"productName":"parentObjectId","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":`${checkoutCreated._id}`,"paymentMethod":"new value"});
const orderProductCreated = await app.service("orderProduct").Model.create({"requestNumber":"new value","requestType":["new value"],"orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.450Z","tax":23,"productName":"parentObjectId","categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":"parentObjectId","paymentMethod":"new value"});

  beforeEach(async () => {
    thisService = await app.service("returnsRefunds");

    // Create users here
    usersServiceResults = await app.service("users").Model.create(usersRefData);
    users = {
      createdBy: usersServiceResults[0]._id,
      updatedBy: usersServiceResults[0]._id,
    };
  });

  after(async () => {
    if (usersServiceResults) {
      await Promise.all(
        usersServiceResults.map((i) =>
          app.service("users").Model.findByIdAndDelete(i._id)
        )
      );
    }
  });

  it("registered the service", () => {
    assert.ok(thisService, "Registered the service (returnsRefunds)");
  });

  describe("#create", () => {
    const options = {"requestNumber":"new value","requestType":["new value"],"orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.449Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.449Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.450Z","tax":23,"productName":`${orderProductCreated._id}`,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.449Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":"parentObjectId","paymentMethod":"new value","reason":"new value","productDetail":"new value","photos":"new value","conditon":["new value"],"refundMethod":["new value"],"refundAmount":23,"refundRef":"new value","dateReturn":"2026-10-01T15:57:14.451Z","requestedAt":"2026-10-01T15:57:14.451Z","refundedAt":"2026-10-01T15:57:14.451Z"};

    beforeEach(async () => {
      returnsRefundCreated = await thisService.Model.create({...options, ...users});
    });

    it("should create a new returnsRefund", () => {
      assert.strictEqual(returnsRefundCreated.requestNumber, options.requestNumber);
assert.strictEqual(returnsRefundCreated.requestType, options.requestType);
assert.strictEqual(returnsRefundCreated.orderNumber.toString(), options.orderNumber.toString());
assert.strictEqual(returnsRefundCreated.productName.toString(), options.productName.toString());
assert.strictEqual(returnsRefundCreated.customerName.toString(), options.customerName.toString());
assert.strictEqual(returnsRefundCreated.reason, options.reason);
assert.strictEqual(returnsRefundCreated.productDetail, options.productDetail);
assert.strictEqual(returnsRefundCreated.photos, options.photos);
assert.strictEqual(returnsRefundCreated.conditon, options.conditon);
assert.strictEqual(returnsRefundCreated.status, options.status);
assert.strictEqual(returnsRefundCreated.refundMethod, options.refundMethod);
assert.strictEqual(returnsRefundCreated.refundAmount, options.refundAmount);
assert.strictEqual(returnsRefundCreated.refundRef, options.refundRef);
assert.strictEqual(returnsRefundCreated.dateReturn.toISOString(), options.dateReturn);
assert.strictEqual(returnsRefundCreated.requestedAt.toISOString(), options.requestedAt);
assert.strictEqual(returnsRefundCreated.refundedAt.toISOString(), options.refundedAt);
    });
  });

  describe("#get", () => {
    it("should retrieve a returnsRefund by ID", async () => {
      const retrieved = await thisService.Model.findById(returnsRefundCreated._id);
      assert.strictEqual(retrieved._id.toString(), returnsRefundCreated._id.toString());
    });
  });

  describe("#update", () => {
    const options = {"requestNumber":"updated value","requestType":["updated value"],"orderNumber":`${orderProductCreated._id}`,"productName":`${orderProductCreated._id}`,"customerName":`${customerCreated._id}`,"reason":"updated value","productDetail":"updated value","photos":"updated value","conditon":["updated value"],"status":["updated value"],"refundMethod":["updated value"],"refundAmount":100,"refundRef":"updated value","dateReturn":"2026-10-01T15:57:14.451Z","requestedAt":"2026-10-01T15:57:14.451Z","refundedAt":"2026-10-01T15:57:14.451Z"};

    it("should update an existing returnsRefund ", async () => {
      const returnsRefundUpdated = await thisService.Model.findByIdAndUpdate(
        returnsRefundCreated._id, 
        options, 
        { new: true } // Ensure it returns the updated doc
      );
      assert.strictEqual(returnsRefundUpdated.requestNumber, options.requestNumber);
assert.strictEqual(returnsRefundUpdated.requestType, options.requestType);
assert.strictEqual(returnsRefundUpdated.orderNumber.toString(), options.orderNumber.toString());
assert.strictEqual(returnsRefundUpdated.productName.toString(), options.productName.toString());
assert.strictEqual(returnsRefundUpdated.customerName.toString(), options.customerName.toString());
assert.strictEqual(returnsRefundUpdated.reason, options.reason);
assert.strictEqual(returnsRefundUpdated.productDetail, options.productDetail);
assert.strictEqual(returnsRefundUpdated.photos, options.photos);
assert.strictEqual(returnsRefundUpdated.conditon, options.conditon);
assert.strictEqual(returnsRefundUpdated.status, options.status);
assert.strictEqual(returnsRefundUpdated.refundMethod, options.refundMethod);
assert.strictEqual(returnsRefundUpdated.refundAmount, options.refundAmount);
assert.strictEqual(returnsRefundUpdated.refundRef, options.refundRef);
assert.strictEqual(returnsRefundUpdated.dateReturn.toISOString(), options.dateReturn);
assert.strictEqual(returnsRefundUpdated.requestedAt.toISOString(), options.requestedAt);
assert.strictEqual(returnsRefundUpdated.refundedAt.toISOString(), options.refundedAt);
    });
  });

  describe("#delete", async () => {
    it("should delete a returnsRefund", async () => {
      await app
        .service("users")
        .Model.findByIdAndDelete(usersServiceResults._id);

      await app.service("customerAddress").Model.findByIdAndDelete(customerAddressCreated._id);
await app.service("customer").Model.findByIdAndDelete(customerCreated._id);
await app.service("coupons").Model.findByIdAndDelete(couponsCreated._id);
await app.service("productPrice").Model.findByIdAndDelete(productPriceCreated._id);
await app.service("order").Model.findByIdAndDelete(orderCreated._id);
await app.service("typeOfProduct").Model.findByIdAndDelete(typeOfProductCreated._id);
await app.service("inventory").Model.findByIdAndDelete(inventoryCreated._id);
await app.service("productSize").Model.findByIdAndDelete(productSizeCreated._id);
await app.service("productColour").Model.findByIdAndDelete(productColourCreated._id);
await app.service("products").Model.findByIdAndDelete(productsCreated._id);
await app.service("category").Model.findByIdAndDelete(categoryCreated._id);
await app.service("orderProduct").Model.findByIdAndDelete(orderProductCreated._id);
await app.service("checkout").Model.findByIdAndDelete(checkoutCreated._id);;

      const returnsRefundDeleted = await thisService.Model.findByIdAndDelete(returnsRefundCreated._id);
      assert.strictEqual(returnsRefundDeleted._id.toString(), returnsRefundCreated._id.toString());
    });
  });
});