const assert = require("assert");
const app = require("../../src/app");

let usersRefData = [
  {
    name: "Standard User",
    email: "standard@example.com",
    password: "password",
  },
];

describe("reviews service", async () => {
  let thisService;
  let reviewCreated;
  let usersServiceResults;
  let users;

  const customerAddressCreated = await app.service("customerAddress").Model.create({"productName":"parentObjectId","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value"});
const customerCreated = await app.service("customer").Model.create({"productName":"parentObjectId","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":`${customerAddressCreated._id}`,"addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.490Z"});
const customerCreated = await app.service("customer").Model.create({"productName":"parentObjectId","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":"parentObjectId"});
const customerCreated = await app.service("customer").Model.create({"productName":"parentObjectId","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":"parentObjectId"});
const couponsCreated = await app.service("coupons").Model.create({"productName":"parentObjectId","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z"});
const productPriceCreated = await app.service("productPrice").Model.create({"productName":"parentObjectId","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value"});
const orderCreated = await app.service("order").Model.create({"productName":"parentObjectId","orderNumber":"new value","customerName":"new value","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23});
const typeOfProductCreated = await app.service("typeOfProduct").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"new value","typeOfProduct":"parentObjectId","productType":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z"});
const productSizeCreated = await app.service("productSize").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":`${inventoryCreated._id}`,"sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId"});
const productColourCreated = await app.service("productColour").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":"parentObjectId","colorName":"new value","colorCode":"new value"});
const inventoryCreated = await app.service("inventory").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":"new value","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value"});
const productPriceCreated = await app.service("productPrice").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":"parentObjectId"});
const productPriceCreated = await app.service("productPrice").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":"parentObjectId"});
const productsCreated = await app.service("products").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":"parentObjectId","variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":`${productPriceCreated._id}`,"status":["new value"]});
const categoryCreated = await app.service("category").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":"parentObjectId","typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"new value","sku":`${inventoryCreated._id}`,"stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":`${productSizeCreated._id}`,"sizeCategory":"new value","sizeValue":"new value","productStock":`${inventoryCreated._id}`,"productColour":`${productColourCreated._id}`,"colorName":"new value","colorCode":"new value","price":`${productPriceCreated._id}`,"afterDiscount":`${productPriceCreated._id}`,"status":["new value"]});
const productsCreated = await app.service("products").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"]});
const typeOfProductCreated = await app.service("typeOfProduct").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"new value","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value"});
const productPriceCreated = await app.service("productPrice").Model.create({"productName":"new value","orderNumber":`${orderCreated._id}`,"customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":`${customerCreated._id}`,"phoneContact":`${customerCreated._id}`,"subtotal":23,"coupon":`${couponsCreated._id}`,"couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":`${productPriceCreated._id}`,"basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.491Z","tax":23,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId"});
const orderCreated = await app.service("order").Model.create({"productName":"new value","orderNumber":"new value","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":23,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.492Z","tax":23,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":`${typeOfProductCreated._id}`,"description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":`${productPriceCreated._id}`,"netTotal":"parentObjectId"});
const orderProductCreated = await app.service("orderProduct").Model.create({"productName":"parentObjectId","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":"parentObjectId","coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.492Z","tax":23,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":"parentObjectId","paymentMethod":"new value"});
const checkoutCreated = await app.service("checkout").Model.create({"productName":"parentObjectId","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.492Z","tax":23,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":"parentObjectId","paymentMethod":"new value"});
const orderProductCreated = await app.service("orderProduct").Model.create({"productName":"parentObjectId","orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.492Z","tax":23,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":`${checkoutCreated._id}`,"paymentMethod":"new value"});

  beforeEach(async () => {
    thisService = await app.service("reviews");

    // Create users here
    usersServiceResults = await app.service("users").Model.create(usersRefData);
    users = {
      createdBy: usersServiceResults[0]._id,
      updatedBy: usersServiceResults[0]._id,
    };
  });

  after(async () => {
    if (usersServiceResults) {
      await Promise.all(
        usersServiceResults.map((i) =>
          app.service("users").Model.findByIdAndDelete(i._id)
        )
      );
    }
  });

  it("registered the service", () => {
    assert.ok(thisService, "Registered the service (reviews)");
  });

  describe("#create", () => {
    const options = {"productName":`${orderProductCreated._id}`,"orderNumber":"parentObjectId","customerName":"parentObjectId","email":"new value","phoneNumber":23,"address":"parentObjectId","addressType":"new value","addressLine1":"new value","addressLine2":"new value","city":"new value","postalCode":23,"country":"new value","joinedAt":"2026-10-01T15:57:14.491Z","emailContact":"parentObjectId","phoneContact":"parentObjectId","subtotal":`${orderProductCreated._id}`,"coupon":"parentObjectId","couponName":"new value","couponCode":"new value","minimumOrder":"new value","validUntil":"2026-10-01T15:57:14.491Z","discount":"parentObjectId","basePrice":23,"discountPrice":23,"taxPercentage":"new value","shippingFee":23,"placedOrderDate":"2026-10-01T15:57:14.492Z","tax":23,"categoryName":`${categoryCreated._id}`,"typeOfProduct":`${typeOfProductCreated._id}`,"productType":"parentObjectId","description":"new value","image":"new value","showInMenu":["new value"],"productsTotal":`${productsCreated._id}`,"variantName":"parentObjectId","sku":"parentObjectId","stockType":"new value","stockQuantity":23,"reservedQuantity":23,"availableQuantity":23,"updatedAt":"2026-10-01T15:57:14.491Z","productSize":"parentObjectId","sizeCategory":"new value","sizeValue":"new value","productStock":"parentObjectId","productColour":"parentObjectId","colorName":"new value","colorCode":"new value","price":"parentObjectId","afterDiscount":"parentObjectId","status":["new value"],"quantity":"new value","unitPrice":"parentObjectId","netTotal":`${checkoutCreated._id}`,"paymentMethod":"new value","rating":23,"isVerified":true};

    beforeEach(async () => {
      reviewCreated = await thisService.Model.create({...options, ...users});
    });

    it("should create a new review", () => {
      assert.strictEqual(reviewCreated.productName.toString(), options.productName.toString());
assert.strictEqual(reviewCreated.customerName.toString(), options.customerName.toString());
assert.strictEqual(reviewCreated.rating, options.rating);
assert.strictEqual(reviewCreated.description, options.description);
assert.strictEqual(reviewCreated.isVerified, options.isVerified);
assert.strictEqual(reviewCreated.isVerified, options.isVerified);
assert.strictEqual(reviewCreated.status, options.status);
    });
  });

  describe("#get", () => {
    it("should retrieve a review by ID", async () => {
      const retrieved = await thisService.Model.findById(reviewCreated._id);
      assert.strictEqual(retrieved._id.toString(), reviewCreated._id.toString());
    });
  });

  describe("#update", () => {
    const options = {"productName":`${orderProductCreated._id}`,"customerName":`${customerCreated._id}`,"rating":100,"description":"updated value","isVerified":false,"status":["updated value"]};

    it("should update an existing review ", async () => {
      const reviewUpdated = await thisService.Model.findByIdAndUpdate(
        reviewCreated._id, 
        options, 
        { new: true } // Ensure it returns the updated doc
      );
      assert.strictEqual(reviewUpdated.productName.toString(), options.productName.toString());
assert.strictEqual(reviewUpdated.customerName.toString(), options.customerName.toString());
assert.strictEqual(reviewUpdated.rating, options.rating);
assert.strictEqual(reviewUpdated.description, options.description);
assert.strictEqual(reviewUpdated.isVerified, options.isVerified);
assert.strictEqual(reviewUpdated.isVerified, options.isVerified);
assert.strictEqual(reviewUpdated.status, options.status);
    });
  });

  describe("#delete", async () => {
    it("should delete a review", async () => {
      await app
        .service("users")
        .Model.findByIdAndDelete(usersServiceResults._id);

      await app.service("customerAddress").Model.findByIdAndDelete(customerAddressCreated._id);
await app.service("customer").Model.findByIdAndDelete(customerCreated._id);
await app.service("coupons").Model.findByIdAndDelete(couponsCreated._id);
await app.service("productPrice").Model.findByIdAndDelete(productPriceCreated._id);
await app.service("order").Model.findByIdAndDelete(orderCreated._id);
await app.service("typeOfProduct").Model.findByIdAndDelete(typeOfProductCreated._id);
await app.service("inventory").Model.findByIdAndDelete(inventoryCreated._id);
await app.service("productSize").Model.findByIdAndDelete(productSizeCreated._id);
await app.service("productColour").Model.findByIdAndDelete(productColourCreated._id);
await app.service("products").Model.findByIdAndDelete(productsCreated._id);
await app.service("category").Model.findByIdAndDelete(categoryCreated._id);
await app.service("orderProduct").Model.findByIdAndDelete(orderProductCreated._id);
await app.service("checkout").Model.findByIdAndDelete(checkoutCreated._id);;

      const reviewDeleted = await thisService.Model.findByIdAndDelete(reviewCreated._id);
      assert.strictEqual(reviewDeleted._id.toString(), reviewCreated._id.toString());
    });
  });
});